### PR TITLE
feat(rewrite)

### PR DESCRIPTION
**Pull request by thibaultCha**
This is a complete rewrite of the library, to the exception of the serializers. This rewrite was motivated by #11 and Mashape/kong#660, and brings cluster awareness to the driver, along many other things inspired by the official Datastax drivers.

### Summary

- Cluster topology auto detection (contact_points are not used as the only available nodes like it was the case before)
- New cluster awareness capabilities (the driver detects healthy and unhealthy nodes and routes the requests according to it)
- Still usable in both ngx_lua and plain Lua, still uses the cosocket API in ngx_lua and have the same features: simple, prepared, batch statements, same returned values on results etc...
- Cluster awareness is stored using the `ngx.shared.DICT` API, providing cluster informations to all nginx workers at the same time.
- Configurable load balancing, reconnection and retry policies. The only implemented load balancing policy is currently a simple Round Robin (shared across the nginx workers).
- Waiting for schema consensus between nodes when executing DML statements
- Binary protocol auto-downgrade for C* 2.0 (which only supports protocol v2)
- A lot more options to be configured on a per-session/per-request basis
- Nginx integration tests (along with pure Lua unit and integration tests with Busted)
- Overall, a better architecture and probably other things I did not mention here

The purpose is now to have cluster informations retrieved in `init_by_lua` in ngx_lua, stored in `ngx.shared.DICT`, and then use short-lived, cheap "sessions" that leverage the cosocket API during other phases. See example in README.

### TODO

before releasing:
- [x] implement mutex on shm accesses with potential concurrency issues
- [x] death proof error handling

not priorities:
- support query tracing
- support protocol v3 named parameters for requests binding
- documentation, documentation (luadoc and update website)
- support for refreshing cluster infos/nodes joining/leaving
- provide a way to flush the shm dicts on session/cluster shutdown

### CODE REVIEW

**Comment by LewisJEllis** [comment]
Great work! I read through the core of this and some of the tests, and it looks really nice. I'm excited to see this (much-needed upgrade) land in Kong.

**Comment by thibaultCha** [comment]
Thanks! Yes, it still needs some polishing and a lot more of testing before landing in Kong, but I hope to make this happen very soon.

**Comment by alubbe** [comment]
Thanks for pointing me towards this new repo. From the new example https://github.com/thibaultCha/lua-cassandra/blob/feat/rewrite/README.md#usage, would it make sense to open a global session via init_by_lua rather than new local sessions for each location?
Also, what's the rough ETA for this PR?

**Comment by thibaultCha** [comment]
No, that would be terrible for performance since all the workers would fight for the same resources. ngx_lua is non blocking only if each request is processed in its isolated state and if you're not doing blocking operations on top of it. 

Probably soon. It hasn't been tested in production but I think it is already usable.

**Comment by thibaultCha** [comment]
Alright, I am satisfied enough with this to release 0.4.0 and include it in Kong. After some more production usage and a few missing features, this will be bumped to 1.0.

**Pull request merged**
